# Generated by Django 5.2.6 on 2025-09-15 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('countries', models.CharField(max_length=255)),
                ('director', models.CharField(max_length=255)),
                ('actors', models.TextField()),
                ('duration_minutes', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('star_5', models.IntegerField(default=0)),
                ('star_4', models.IntegerField(default=0)),
                ('star_3', models.IntegerField(default=0)),
                ('star_2', models.IntegerField(default=0)),
                ('star_1', models.IntegerField(default=0)),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('poster', models.ImageField(blank=True, null=True, upload_to='posters/')),
                ('genres', models.ManyToManyField(related_name='movies', to='frontend.genre')),
            ],
        ),
    ]
